version: '3.7'

services:
  app:
    image: expressjs-realworld-example-app
    build:
      dockerfile: zbuild.yml
      context: .
      target: prod
    restart: on-failure
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://db/app
      - SECRET=somesecret

  db:
    image: mongo
