version: '3.7'

services:
  app:
    image: svelte-realworld-example-app/app
    build:
      dockerfile: zbuild.yml
      context: .
      target: prod
    restart: on-failure
    ports:
      - 80:3000
    environment:
      # @TODO: this should be set in this image
      # - NODE_ENV=production
      - PORT=3000
