# syntax=akerouanton/zbuilder:200419-03
kind: php
version: 7.3
alpine: true
# @TODO: check base + version
# base: php:7.3-fpm-buster
# base: php@sha256:db5bce28b6eabd8bd963cfd95131a01171acea9cff500447bb8d9e05afd34e4b
fpm: true

global_deps:
  symfony/flex: '*'

extensions:
  intl: "*"
  pdo_pgsql: "*"

source_context:
  type: git
  source: github.com/api-platform/demo
  path: api

sources:
  - bin/console
  - config/
  - fixtures/
  - public/
  - src/

config_files:
  fpm.conf: "${fpm_conf}"
  php.ini: "${php_ini}"

stateful_dirs:
  - var/

integrations:
  - blackfire

post_install:
  - echo '<?php return [];' > .env.local.php
  - mkdir -p var/cache
  - APP_ENV=prod composer run-script --no-dev post-install-cmd

stages:
  # @TODO: find a way to disable dev env as it's not useful for this example
  dev: {}
  prod:
    extensions:
      apcu: "5.1.17"
  consumer:
    derive_from: prod
    command: ["bin/console", "messenger:consume"]
    healthcheck: false

webserver:
  type: nginx
  alpine: true
  config_files:
    nginx.conf: "${nginx_conf}"
  assets:
    - from: public/
      to: /app/public/
